# Generated by Django 5.2.4 on 2025-08-27 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lucky_draw', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='qr_code',
        ),
    ]
